### ISSUE TITLE
Highlight group Label has the same color as regular text

### ISSUE THREAD

**Issue by sro5h** [protesilaos/prot16#7]
E.g. the keywords `case` and `default` in c++ don't get highlighted.

**Comment by sro5h** [comment]
The highlight group Float has the same color as regular text aswell, resulting in integral numbers being highlighted but not floating numbers.

**Comment by protesilaos** [comment]
Thank you for the feedback. 

1. Can you please tell me what text editor you are using?
2. Can you share some demo with the issue?

**Comment by sro5h** [comment]
I use vim, e.g. editing a c++ file containing:
```c++
class SomeClass final {
public:
        ~SomeClass() = default;
};
```
Here the keyword `default` is not highlighted

Or for the number issue:
`int a = 3;` <- 3 is highlighted
`float b = 3.4516f` <- 3.4516 has the normal text color

**Comment by protesilaos** [comment]
Made some changes. Here a couple of screenshots using Gaia Dark/Light. This is Vim running in the console.

![2018-12-10_18 09 20_1920x1062](https://user-images.githubusercontent.com/12828033/49745314-8d41e500-fc96-11e8-8fbc-e4878bf5cf32.png)

![2018-12-10_18 11 09_1920x1062](https://user-images.githubusercontent.com/12828033/49745318-916e0280-fc96-11e8-817f-c57dd7bc3373.png)

Is this closer to the desired result? I shall push the changes later on today.

**Comment by sro5h** [comment]
Yes :) that's perfect, thank you very much

**Comment by protesilaos** [comment]
I just updated this repo and the [one specific to Vim](https://github.com/protesilaos/prot16-vim). Thanks again for your feedback!

By the by, I realised that I have not touched this project in about a year. There are all sorts of things I learned from my more recent [Tempus Themes](https://gitlab.com/protesilaos/tempus-themes) project. I will incorporate all the improvements as soon as I can.

**Comment by sro5h** [comment]
Sounds good :) i'll have a look at your tempus themes project
